name: Formater

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  Formater:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          
      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
      
      - name: Remove old folders
        run: |
          rm -rf format-socks5.txt
          
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install requests
      
      - name: Start Format Socks5 Proxy
        run: |
          python format-socks5.py
          
      - name: Commit and push
        run: |
          git add .
          
          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi
          
          git commit -m "Updated proxies $(date)"
          git pull --rebase origin main || true
          git push
